apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring
data:
  config.alloy: |
    loki.write "victorialogs" {
      endpoint {
        url = "http://victoria-logs.monitoring.svc:9428/insert/loki/api/v1/push"
      }
    }

    loki.source.file "k8s_containers" {
      targets = [{ __path__ = "/var/log/containers/*.log" }]
      forward_to = [loki.write.victorialogs.receiver]
    }

    loki.source.file "k8s_pods" {
      targets = [{ __path__ = "/var/log/pods/*/*/*.log" }]
      forward_to = [loki.write.victorialogs.receiver]
    }

    prometheus.scrape "ingress" {
      targets = [{ __address__ = "ingress-nginx-controller.ingress-nginx.svc:10254" }]
      job_name = "ingress-nginx"
      scrape_interval = "30s"
      forward_to = [prometheus.remote_write.vm.receiver]
    }

    prometheus.remote_write "vm" {
      endpoint { url = "http://victoria-metrics.monitoring.svc:8428/api/v1/write" }
    }