apiVersion: v1
kind: ServiceAccount
metadata:
  name: waf-admin-sa
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: waf-admin-monitoring-role
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get","list","create","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: waf-admin-monitoring-rb
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: waf-admin-sa
    namespace: monitoring
roleRef:
  kind: Role
  name: waf-admin-monitoring-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: waf-admin-ingress-role
  namespace: ingress-nginx
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get","list","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: waf-admin-ingress-rb
  namespace: ingress-nginx
subjects:
  - kind: ServiceAccount
    name: waf-admin-sa
    namespace: monitoring
roleRef:
  kind: Role
  name: waf-admin-ingress-role
  apiGroup: rbac.authorization.k8s.io